apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
    - host: guestbook.info
      http:
        paths:
          - path: /
            backend:
              serviceName: gateway-service
              servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: book-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 8081
      port: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-deployment
spec:
  selector:
    matchLabels:
      app: book-pod
  template:
    metadata:
      labels:
        app: book-pod
    spec:
      containers:
        - name: book-container
          image: huyto000/booklisting:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: film-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 8082
      port: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: film-deployment
spec:
  selector:
    matchLabels:
      app: film-pod
  template:
    metadata:
      labels:
        app: film-pod
    spec:
      containers:
        - name: film-container
          image: huyto000/filmlisting:latest
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 8080
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  selector:
    matchLabels:
      app: gateway-pod
  template:
    metadata:
      labels:
        app: gateway-pod
    spec:
      containers:
        - name: gateway-container
          image: huyto000/gateway:latest
          ports:
            - containerPort: 8080
