server:
  port: 8080

---
spring:
  profile: local
  cloud:
    gateway:
      routes:
        - id: book
          uri: http://localhost:8081/
          predicates:
          - Path=/book/**


        - id: film
          uri: http://localhost:8082/
          predicates:
          - Path=/film/**
          filters:
          - name: RequestRateLimiter
            args:
              redis-rate-limiter:
                replenishRate: 1000
                burstCapacity: 2000
                requestedTokens: 1

  main:
    web-application-type: reactive

---

spring:
  profile: k8s
  cloud:
    gateway:
      routes:
        - id: book
          uri: http://book-service:8081/
          predicates:
            - Path=/book/**


        - id: film
          uri: http://film-service:8082/
          predicates:
            - Path=/film/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter:
                  replenishRate: 1000
                  burstCapacity: 2000
                  requestedTokens: 1
  redis:
    database: 0
    host: localhost
    port: 6379
  main:
    web-application-type: reactive
---